### ISSUE TITLE
Consumer Tag

### ISSUE THREAD

**Issue by thaoula** [coders51/rabbitmq-stream-js-client#180]
Hi Team,

Thanks for your hard work on the this client. 

I have been trying to update some of our existing stream connections using the Rascal library and AMQP 0.9.1 to your new stream client.

Is it possible to set the consumer Tag? 

![image](https://github.com/coders51/rabbitmq-stream-js-client/assets/349133/2f3ca03a-9b4f-4a72-b5cb-9063f8767e04)

The consumerRef only appears in the connection.

Regards,
Tarek

**Comment by tarzacodes** [comment]
I've checked and double checked - sadly, there isn't any way to set the consumer tag with the streams protocol at the current moment. That means, that we cannot implement this, at least for now :disappointed:

**Comment by Gsantomaggio** [comment]
With the stream protocol, you don't need to know the consumer TAG since you can't remove the consumer based on the consumer tag.

If you need to identify the consumer, you can use the `Reference`  field.

Or we can thing something similar we did for the .NET stream client https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/pull/348
