### ISSUE TITLE
Exposing offset operations on the client

### ISSUE THREAD

**Issue by l4mby** [coders51/rabbitmq-stream-js-client#206]
We should also expose `queryOffset` as an operation that can be done from the rabbitmq client

**Comment by tarzacodes** [comment]
Adding some context for clarity (me and @l4mby discussed this) - the problem is that, as of now, only the consumer can query for the offset. So, if we want to start a new consumer that starts from whenever the last consumer with the same `consumerRef` left off, we would have to create a new consumer with an arbitrary starting offset, query the offset, close the consumer, reopen a second consumer with the actual numeric offset we got by querying the server. Which is obviously ridiculous and not very user friendly. So we expose the `queryOffset` feature directly in the client.

**Comment by Gsantomaggio** [comment]
See: https://rabbitmq.github.io/rabbitmq-stream-dotnet-client/stable/htmlsingle/index.html#_query_streamsuperstream

Like:
```
system.QueryOffset(....)
```


same in golang:
```
offset, err := env.QueryOffset("consumer_name", "streamName")
```
